Add (some) google resource support
kishaningithub/tf-import-gen pull request #36
Opened 2024-11-08 16:21 UTC by fiskhest

I was mildly saddened when I realised this utility would not be able to help me perform a major migration within $COMPANY terraform states. With the help of a colleague, this PR contains support for generating the imports for resources we found, together with tests.

This is not a complete implementation supporting all google resources, but a starting point for anyone else that does google migrations, adding new ones is pretty straight forward.

Maybe adding a minor hint to the README about the coverage not being 100% would be nice, it took me some time to figure out why the imports this generated was total bologna. 🍝 

- [x] `make fmt`
- To run only the tests, run command `make test`
```
go test -race -v ./...
?       github.com/kishaningithub/tf-import-gen [no test files]
=== RUN   Test_ComputeTerraformImportForResource
=== RUN   Test_ComputeTerraformImportForResource/For_aws_iam_role_policy_attachment
=== RUN   Test_ComputeTerraformImportForResource/For_aws_lambda_permission
=== RUN   Test_ComputeTerraformImportForResource/For_aws_security_group_rule_with_source_security_group_id
=== RUN   Test_ComputeTerraformImportForResource/For_aws_security_group_rule_with_cidr_blocks
=== RUN   Test_ComputeTerraformImportForResource/For_aws_security_group_rule_with_prefix_list_ids
=== RUN   Test_ComputeTerraformImportForResource/For_aws_api_gateway_resource
=== RUN   Test_ComputeTerraformImportForResource/For_aws_api_gateway_deployment
=== RUN   Test_ComputeTerraformImportForResource/For_aws_api_gateway_stage
=== RUN   Test_ComputeTerraformImportForResource/For_aws_api_gateway_method_settings
=== RUN   Test_ComputeTerraformImportForResource/For_aws_cloudwatch_event_target
=== RUN   Test_ComputeTerraformImportForResource/For_aws_api_gateway_method
=== RUN   Test_ComputeTerraformImportForResource/For_aws_api_gateway_integration
=== RUN   Test_ComputeTerraformImportForResource/For_aws_route_table_association
=== RUN   Test_ComputeTerraformImportForResource/For_aws_iam_user_policy_attachment
=== RUN   Test_ComputeTerraformImportForResource/For_aws_emr_instance_group
=== RUN   Test_ComputeTerraformImportForResource/For_aws_backup_selection
=== RUN   Test_ComputeTerraformImportForResource/For_aws_vpc_endpoint_route_table_association
=== RUN   Test_ComputeTerraformImportForResource/For_aws_cognito_user_pool_client
=== RUN   Test_ComputeTerraformImportForResource/For_aws_ecs_cluster
=== RUN   Test_ComputeTerraformImportForResource/For_aws_ecs_task_definition
=== RUN   Test_ComputeTerraformImportForResource/For_aws_wafv2_web_acl
=== RUN   Test_ComputeTerraformImportForResource/For_aws_autoscaling_schedule
=== RUN   Test_ComputeTerraformImportForResource/For_aws_appautoscaling_target
=== RUN   Test_ComputeTerraformImportForResource/For_aws_appautoscaling_policy
=== RUN   Test_ComputeTerraformImportForResource/For_aws_ecs_service
=== RUN   Test_ComputeTerraformImportForResource/For_google_monitoring_alert_policy
=== RUN   Test_ComputeTerraformImportForResource/For_google_monitoring_notification_channel
=== RUN   Test_ComputeTerraformImportForResource/For_google_service_account_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_service_account_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_privateca_ca_pool_iam_member.pool
=== RUN   Test_ComputeTerraformImportForResource/For_google_privateca_certificate_template_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_project_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_project_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_sql_database_instance
=== RUN   Test_ComputeTerraformImportForResource/For_google_sql_user
=== RUN   Test_ComputeTerraformImportForResource/For_google_iap_tunnel_instance_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_bigquery_dataset_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_bigquery_table_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_kms_crypto_key_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_kms_crypto_key_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_cloud_run_service_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_secret_manager_secret_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_secret_manager_secret_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_storage_bucket_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_storage_bucket_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_compute_subnetwork_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_organization_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_project_iam_custom_role
=== RUN   Test_ComputeTerraformImportForResource/For_google_pubsub_topic_iam_binding
=== RUN   Test_ComputeTerraformImportForResource/For_google_pubsub_topic_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_pubsub_subscription_iam_member
=== RUN   Test_ComputeTerraformImportForResource/For_google_resource_manager_lien
=== RUN   Test_ComputeTerraformImportForResource/For_google_monitoring_uptime_check_config
=== RUN   Test_ComputeTerraformImportForResource/For_everything_else
--- PASS: Test_ComputeTerraformImportForResource (0.01s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_iam_role_policy_attachment (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_lambda_permission (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_security_group_rule_with_source_security_group_id (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_security_group_rule_with_cidr_blocks (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_security_group_rule_with_prefix_list_ids (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_api_gateway_resource (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_api_gateway_deployment (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_api_gateway_stage (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_api_gateway_method_settings (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_cloudwatch_event_target (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_api_gateway_method (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_api_gateway_integration (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_route_table_association (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_iam_user_policy_attachment (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_emr_instance_group (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_backup_selection (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_vpc_endpoint_route_table_association (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_cognito_user_pool_client (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_ecs_cluster (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_ecs_task_definition (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_wafv2_web_acl (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_autoscaling_schedule (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_appautoscaling_target (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_appautoscaling_policy (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_aws_ecs_service (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_google_monitoring_alert_policy (0.00s)
    --- PASS: Test_ComputeTerraformImportForResource/For_google_monitoring_notification_channel (0.00s)
    --- PASS: Test_ComputeTerraformImportForReso [...]

2024-11-11 15:00 UTC, fiskhest commented
Oops, should be sorted now. As for README, I gave it a shot; please leave a suggestion if you prefer some other way of expressing the fact.

2024-11-12 11:27 UTC, kishanbsh-gilead requested changes

2024-11-12 11:27 UTC, kishanbsh-gilead commented on pkg/convertor.go
> +	var condition map[string]any
Given this variable is used only in a smaller subset of resources can this be inlined using `:=` and removed from here?

2024-11-12 11:27 UTC, kishanbsh-gilead commented on pkg/convertor.go
> +		return fmt.Sprint(v("name"))
i think the `fmt.Sprint` can be dropped here and the statement can become `return v("name")`

2024-11-12 11:27 UTC, kishanbsh-gilead commented on pkg/convertor.go
> +	case "google_pubsub_subscription_iam_binding":
I see this resource under the "resource which do not support the import" category above. Should this be removed?

2024-11-12 11:27 UTC, kishanbsh-gilead commented on README.md
> -Tool to generate terraform import statements to simplify state migrations from one terraform code base to another.
I think this can be put in a separate "Note" section in this file.

2024-11-12 13:51 UTC, kishaningithub commented on pkg/convertor.go
> +		if ok && len(conditions) >= 1 {
Can `len(conditions) >= 1` be changed to `len(conditions) > 0` ?

2024-11-13 08:42 UTC, fiskhest commented
🙏🏼 should be the last of it. Thanks! 🎉

2024-11-13 08:54 UTC, kishaningithub approved these changes

2024-11-13 08:55 UTC, kishaningithub commented
Merging it! Thanks a lot for the contribution @fiskhest !

2024-11-13 08:55 UTC, merged